### ISSUE TITLE
Old site?

### ISSUE THREAD

**Issue by luizbills** [Brain-WP/BrainMonkey#126]
I found BrainMonkey in https://brain-wp.github.io/BrainMonkey/ but this repo indicates https://giuseppe-mazzapica.gitbook.io/brain-monkey/

How about redirecting the first to the second (the correct one, right?) or else to this repository.

**Comment by gmazzap** [comment]
Hi @luizbills 

Yes, it makes sense. I don't control the domain that is GitHub pages, so the only way would be to add a single index file with javascript redirection. 

Glad to accept a PR if you (or anyone else) have time.

**Comment by luizbills** [comment]
are you not the owner of https://github.com/Brain-WP?

**Comment by jrfnl** [comment]
> the only way would be to add a single index file with javascript redirection.

Or an HTML redirect ?

```html
<meta http-equiv="refresh" content="0; URL=https://example.com/">
```

Could even be done for all pages in the site - https://christianheilmann.com/2021/08/03/redirecting-github-pages/

**Comment by gmazzap** [comment]
Used HTTP redirect for the home page only. Maintaining the redirect for all pages looked like too much work for the scope, even because if the new site would change and page URL, I would need to also change the redirect.
