### ISSUE TITLE
Calling functions that use named arguments is not supported

### ISSUE THREAD

**Issue by andaniel05** [Brain-WP/BrainMonkey#141]
In the plugin implementation:

```php
		add_submenu_page(
			parent_slug: 'options-general.php',
			page_title: 'My Page Title',
			menu_title: 'My Menu Title',
			capability: 'manage_options',
			menu_slug: 'my-menu-slug',
			callback: array( __CLASS__, 'my_method' ),
		);
```

in the test:

```php
	expect('add_submenu_page')
		->once()
		->with(
			'options-general.php',
			'My Page Title',
			'My Menu Title',
			'manage_options',
			'my-menu-slug',
			[MyClass::class, 'my_method'],
		)
	;
```

When i run PHPUnit:

```
Error: Unknown named parameter $parent_slug
```

**Comment by jrfnl** [comment]
WordPress does not support named parameters in function calls and likely never will.

Until WP _would_ announce support for named parameters (if ever), it is unreasonable to expect this tool to support it, though a best effort is made.

Note: your code as-is will not work on older WordPress versions as [the parameter in question was renamed only last year](https://github.com/WordPress/wordpress-develop/commit/8c1abdcf8aae7e430e2f3bd0c12f9102c69a318f), which is all the more reason why WP does not support named parameters.

Ref: https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
