### ISSUE TITLE
has_filter()/has_action() should also work without callback argument

### ISSUE THREAD

**Issue by Rarst** [Brain-WP/BrainMonkey#18]
Native WP `has_filter()`/`has_action()` can be called without arguments to check if _anything_ is attached to a hook.

Monkey implementation doesn't allow this and insist on checking for a _specific_ callback. This makes it impossible to assert hook has _nothing_ attached to it.

My use case: I temporarily override time zone option by hooking before calling WP API function and unhooking after. The more thorough/broad assertion is to check that I have no leftovers of any kind hooked.

Check for specific callback is possible but it's more prone to error (for example if I make mistake in my assertion and check for non–existing callback it will always pass).

```php
// works
$this->assertFalse( has_filter( 'pre_option_timezone_string', 'DateTimeZone->getName()', 10, 0 ) );

// InvalidArgumentException: A callback is required to add a filter.
$this->assertFalse( has_filter( 'pre_option_timezone_string' ) );
```

**Comment by Giuseppe-Mazzapica** [comment]
This is done with 7dcd5e3 and will be part of 1.4.2 release. Thanks for reporting! @Rarst
