### ISSUE TITLE
Patchwork 2.0

### ISSUE THREAD

**Issue by krodyrobi** [Brain-WP/BrainMonkey#20]
In this version we are allowed to modify internal functions, which I would need to accomplish my task.
Will you update the dependencies for the project?

PR: https://github.com/Brain-WP/BrainMonkey/pull/21

**Comment by Giuseppe-Mazzapica** [comment]
@krodyrobi Thanks for the contribution.

Being a major version change, I want to better test any issue before merging on master and release.

If I merge it on `dev` branch, could you use it from there and please report any issue?

**Comment by krodyrobi** [comment]
Sure.

**Comment by Giuseppe-Mazzapica** [comment]
@krodyrobi Pushed to dev. Of course you can still use composer, just pull Brain Monkey with `"brain/monkey": "dev-dev"`

**Comment by krodyrobi** [comment]
Sorry for the late reply I got off focus with the project.

Unfortunately I'm not able to get Functions::expect() to work.
`ReflectionException: Method Mockery\CompositeExpectation::once() does not exist`

And for me this is the most important part, ensuring a call was made.
Can't say for sure where the issue is but I've made a small reproducible example.
[failing.tar.gz](https://github.com/Brain-WP/BrainMonkey/files/857897/failing.tar.gz)

It doesn't seem to be related to the new php redefinitions, as both a custom and `time` functions have the same behaviour.

**Comment by krodyrobi** [comment]
To follow up on that,

The expect call triggers `Monkey/MockeryBridge.php __call()` with the required data,
on Mockery's side `Mockery/CompositeExpectation.php __call()` never gets called.

**Comment by gmazzap** [comment]
@krodyrobi don't really have time now to sort this out, will look at this as sson as I can...

**Comment by krodyrobi** [comment]
No problem, I'll still look around at least to provide possible insight.

**Comment by gmazzap** [comment]
Version 2 seems to work fine with Patchwork 2, and with last changes in `dev-version/1` seems to work with Patchwork 2 as well.

Will close this after some more tests next days, then release version 1.5 with Patchwork 2 support.

**Comment by gmazzap** [comment]
Patchwork 2 is now in use for v1 and v2 series, I can close this.
