### ISSUE TITLE
Updated PHP versions supported in documentation?

### ISSUE THREAD

**Issue by salcode** [Brain-WP/BrainMonkey#24]
Current documentation says

> Currently, Brain Monkey supports PHP from 5.4.x to 5.6.x.

from https://brain-wp.github.io/BrainMonkey/docs/what-and-why.html

I'm running in PHP `7.0.2`, any objections to changing the documentation from `5.6.x` to `7.0.x`?

I'm happy to write the PR.

**Comment by gmazzap** [comment]
Hi again, @salcode

Branin Monkey is tested on Travis up to 7.1, the docs were simply outated. As it was a very simple fix I did it myself.

Thanks for reporting!
