### ISSUE TITLE
Support @expectDeprecated?

### ISSUE THREAD

**Issue by GaryJones** [Brain-WP/BrainMonkey#27]
Here's my unit test:

```php
class Deprecated_Test extends TestCase {

	/**
	 * Test Genesis contributors array.
	 *
	 * @group contributors
	 * @expectedDeprecated genesis_contributors
	 */
	public function test_genesis_contributors() {
		$contributors = genesis_contributors();

		$this->assertGreaterThan( 1, count( $contributors ), 'If there are not at least two contributors for a Genesis cycle, something is wrong.' );

		// Loop through and perform tests on each contributor.
		array_walk( $contributors, function ( $c ) {
			$this->assertTrue( is_array( $c ), 'One of the contributors is not an array' );
			$this->assertArrayHasKey( 'name', $c, 'One of the contributors lacks a name' );
			$this->assertArrayHasKey( 'url', $c, 'One of the contributors lacks a URL' );
			$this->assertArrayHasKey( 'gravatar', $c, 'One of the contributors lacks a Gravatar' );
			$this->assertRegExp( '#^https?://#', $c['url'], 'A contributor URL looks wrong' );
			$this->assertRegExp( '#^https://0\.gravatar\.com/avatar/[a-f0-9]{32}\?s=120#', $c['gravatar'], 'A contributor Gravatar URL is malformed' );
		} );
	}
}
```

When `TestCase` extends `WP_UnitTestCase` (i.e. testing in an WordPress environment), the test passes.
When `TestCase` extends `PHPUnit_Framework_TestCase` (i.e. not in a WordPress environment), the test fails. This is due to the WordPress handling of the `@expectedDeprecated` annotation.

Is this something that BrainMonkey could handle as well?

**Comment by gmazzap** [comment]
I'm not in love with annotations, honestly, and I'm not completely sure, but I think the only way would be to provide a custom base test case class, which I don't want to do either.

Maybe I could think about adding a trait like:

```php
namespace Brain\Wp;

trait DeprecatedSupport {

	public function expectDeprecatedFunction($function) {
		$this->expectDeprecatedThing('function', $function);
	}

	public function expectDeprecatedConstructor($class) {
		$this->expectDeprecatedThing('constructor', $class);
	}

	public function expectDeprecatedArgument($argument) {
		$this->expectDeprecatedThing('argument', $argument);
	}

	public function expectDeprecatedHook($hook) {
		$this->expectDeprecatedThing('hook', $hook);
	}

	protected function expectDeprecatedThing($thing, $subject) {
                // this is both a check and prevent `trigger_error` to run and fail the test
		Filters::expectApplied("deprecated_{$thing}_trigger_error")
		       ->andReturn(false)
		       ->atLeast()
		       ->once();
                // this is to check we are expecting deprecation of the right thing
		Actions::expectFired("deprecated_{$thing}_run")
		       ->with($subject)
		       ->atLeast()
		       ->once();
	}
}
```

with that trait `use`d in your test class, your test method would become:

```php
	/**
	 * Test Genesis contributors array.
	 *
	 * @group contributors
	 */
	public function test_genesis_contributors() {

		$this->expectDeprecatedFunction('genesis_contributors');
		$contributors = genesis_contributors();
                // rest of the test here...
	}
```

The trait could even be used in your base test class, to avoid using it in every test class.

One of the immediate benefit I can think of, compared to annotation, is that for classes I could use PHP 5.5+ `::class` syntax:

```php
    $this->expectDeprecatedConstructor( Foo::class );
```

without the need of using FQCN in the annotation and getting chance to leverage refactoring capability of the IDE in case the class got renamed.

---

Opinions?

**Comment by gmazzap** [comment]
On a second thought all of this does not seem necessary at all.

Brain Monkey is normally used _without_ WordPress being loaded.

It means, that the function `_deprecated_function` (or `_deprecated_file`, `_deprecated_hook`, `_deprecated_argument`...) does *not* exist, so there no `trigger_error()` being called that makes the test fail.

So, using a deprecated function only makes the test fail if  WordPress _is_ loaded. And in many cases, if WordPress is loaded, one does not want to use Brain Monkey at all.

But assuming that for any reason one wants to load WordPress for tests _and_ Brain Monkey it could be possible to just do:

```php
Functions\when('_deprecated_function')->justReturn();
```

or, to check that the deprecation is actually called,

```php
Functions\expect('_deprecated_function')->with('genesis_contributors')->once();
```

and the WordPress function would be redefined making the test pass (because `trigger_error` never gets called).

Considering that the usage of Brain Monkey in combination with WordPress is an edge case, I think it does not worth to add a trait for this. It's a one-liner, after all.

Going to close the issue. Feel free to re-open if I missed something.

**Comment by GaryJones** [comment]
```php
Functions::expect('_deprecated_function')->with('genesis_contributors', '2.5.0', 'Genesis_Contributors::find_contributors')->once();
```

...works, though the presence of the `@expectedDeprecation` causes it's own failure, as the usual deprecation notice isn't triggered.

I agree that tests would typically either use WP, or Brain Monkey, but in the case of Genesis, which has a non-ideal bootstrapping procedure, WP is always needed, even for unit tests where I want to make use of Brain Monkey.

**Comment by tfrommen** [comment]
@GaryJones this sounds like you maybe should revisit the bootstrap routine, no?

**Comment by GaryJones** [comment]
If it were my product, sure, but it's not :-)
