### ISSUE TITLE
ERROR: fseek() stream does not support seeking while not using BrainMonkey

### ISSUE THREAD

**Issue by zengheng3** [Brain-WP/BrainMonkey#31]
I wanted to create a test suit for Wordpress which includes [lucatume/WP-Browser](https://github.com/lucatume/wp-browser), BrainMonkey and [Robo](https://github.com/consolidation/Robo/). I put them in the same composer vendor. Robo is a tool for executing commands, when I tried to test a tiny command in Robo, this error occured. And I tested some other commands but this error appeared after each execution. The strange thing is, I just didn't use any fonction of BrainMonkey. Here is the screenshot for the error :
![image](https://user-images.githubusercontent.com/7296917/28576845-4bce1b66-7155-11e7-92f6-9b4d57df672c.png)
Then I tried to remove dependencies, when I removed BrainMonkey 2.0.2, everything worked fine. I also tried BrainMonkey 1.5.0 and this one works fine.
Here are the dependencies of my composer.json file:
![image](https://user-images.githubusercontent.com/7296917/28577291-a5fdf786-7156-11e7-9035-07c99374af04.png)

I really want to use BrainMonkey 2.0, please help me out, thank you.

**Comment by gmazzap** [comment]
@zengheng3 I have been reported of some issues by loading Patchwork from autoloader.

Your case seems another possible issue of this kind.

I just pushed a branch named `patchwork-load-env` whic allow to disable the autoload of Patchwork by setting an environment variable: `BRAINMONKEY_PATCHWORK_NO_AUTOLOAD`.

If you require BrainMonkey from `dev-patchwork-load-env` than you could try to run your Robo commands after the env var is set. e.g. something like:

```shell
export BRAINMONKEY_PATCHWORK_NO_AUTOLOAD=1 && robo some-command
```

If it works for you, this could be a good step to solve the issue.

**Comment by zengheng3** [comment]
I tried this solution and it works well, but I think this should be a default behavior, setting such a long variable before every execution is really annoying. I saw that lucatume/WP-Browser uses antecedent/patchwork too but this error didn't occured.

**Comment by gmazzap** [comment]
Sure. I am concerned that now removing the autoload could be a breaking change. I have to do some tests.

**Comment by gmazzap** [comment]
This is old. Brain Monkey v2 does not load Patchwork from autoload anymore.
