### ISSUE TITLE
Docs: Add better support for when no JS is available

### ISSUE THREAD

**Issue by GaryJones** [Brain-WP/BrainMonkey#38]
The sidebar links are hidden behind a `display: none`, which makes them invisible to screen reader users, and inaccessible when there is no JavaScript available.

Suggestion:
- Add a `no-js` body class by default to all pages, and add a small JS immediately after the opening `body` tag which changes it to `js`.
- Use this class to conditionally apply styles which can visibly hide the page links until expanded.
- Use the `no-js` class to conditionally apply styles visibly hide the square orange button that toggles the whole sidebar, since it won't work when no JS is available.

**Comment by gmazzap** [comment]
I decided to move to gitbook to reduce maintenance overhead. Documentation is now available here: https://giuseppe-mazzapica.gitbook.io/brain-monkey/
