### ISSUE TITLE
Website docs are not up to date

### ISSUE THREAD

**Issue by stefanfisk** [Brain-WP/BrainMonkey#53]
I just noticed that `is_wp_error()` and `absint` are not documented at
https://brain-wp.github.io/BrainMonkey/docs/wordpress-tools.html, only in https://github.com/Brain-WP/BrainMonkey/blob/master/docs/wordpress-tools.md.

**Comment by gmazzap** [comment]
I moved to gitbook for documentation, so it will be kept in-sync automatically. You can find the docs here: https://giuseppe-mazzapica.gitbook.io/brain-monkey/

**Comment by stefanfisk** [comment]
Might it also make sense to put some sort of notice on https://brain-wp.github.io/BrainMonkey/? It still ranks quite high for "Brain Monkey", and people are probably linking to it as well.

**Comment by gmazzap** [comment]
Make sense. I should probably do a redirect so that Google can catch up.
