### ISSUE TITLE
Missing i18n functions

### ISSUE THREAD

**Issue by XedinUnknown** [Brain-WP/BrainMonkey#67]
Hi!

Most plugins would somehow internationalize human-readable strings. It would be great therefore if this tool had at least some of the i18n functions of WordPress.

I would be super fine with just a stub of `__()` that returns the first argument unchanged.

Of course, it would be better if we could set some expectations as well.

**Comment by tfrommen** [comment]
I think you are looking for [`Brain\Monkey\Functions\stubTranslationFunctions`](https://github.com/Brain-WP/BrainMonkey/blob/c0c9400cc1255e3c9764001c1bc993e343b9236e/inc/api.php#L139)..?. 🙂

**Comment by XedinUnknown** [comment]
Oh! Possibly, yes! Then maybe the docs need updating? This stuff is not listed [here](https://brain-wp.github.io/BrainMonkey/docs/wordpress-tools.html).

**Comment by gmazzap** [comment]
@XedinUnknown Documentation has been moved here: https://giuseppe-mazzapica.gitbook.io/brain-monkey/ and here the documentation for that function https://giuseppe-mazzapica.gitbook.io/brain-monkey/functions-testing-tools/functions-when-1#pre-defined-stubs-for-translation-functions

The reason why you don't see `stubTranslationFunctions` listed under "Defined functions" you linked, is that list is for functions that exist in WordPress that are also defined in Brain Monkey, but `stubTranslationFunctions` is not a WordPress function...

**Comment by XedinUnknown** [comment]
> The reason why you don't see `stubTranslationFunctions` listed under "Defined functions" you linked, is that list is for functions that exist in WordPress that are also defined in Brain Monkey, but `stubTranslationFunctions` is not a WordPress function.

Indeed, `stubTranslationFunctions()` is not a WP function. But e.g. `__()` is. And that's what I was looking for.

Thanks for the docs link!
