### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by jrfnl** [Brain-WP/BrainMonkey#68]
Would be great if a new release could be tagged so people can start testing their own code properly for compatibility with PHP 7.4, without being bogged down by errors coming from the BrainMonkey framework.

Related #55, #61

**Comment by jrfnl** [comment]
Anything I can do to move this forward ? Would be great if PR #69 could also still be included in the release.

**Comment by jrfnl** [comment]
@gmazzap Ping ? Even just having some idea of when a new tagged release can be expected would be helpful to decide whether or not to switch to `dev-master` for now or to wait a little longer for the release.

**Comment by gmazzap** [comment]
@jrfnl sorry for late answer. I had to take a break from Os because of travel to US for WCUS and then "recover".

I'll release a new version. Will see what of the other issues / PRs can be merged rthere. Thanks a lot, as usual.

**Comment by gmazzap** [comment]
And... done: https://github.com/Brain-WP/BrainMonkey/releases/tag/2.4.0

Thanks a lot again

**Comment by jrfnl** [comment]
Appreciated! Thank you.
