### ISSUE TITLE
Packagist is serving version 2.5.0 ?

### ISSUE THREAD

**Issue by jrfnl** [Brain-WP/BrainMonkey#78]
I can't find a `2.5.0` tag here in the repo, but Packagist seems to think there is one and is serving it when running `composer update`. 

Just thought you should know as this may cause problems in the future if a `2.4.3` release would be tagged.

https://packagist.org/packages/brain/monkey#2.5.0

**Comment by gmazzap** [comment]
Thanks @jrfnl I tagged 2.5 by mistake and then immediately removed, but it seems packagist was fast enough.

I manually updated Packagist and now 2.5 is gone there.

Thanks a lot.
