### ISSUE TITLE
Mocks for deep arguments in the function doesn't work

### ISSUE THREAD

**Issue by wppunk** [Brain-WP/BrainMonkey#89]
```
expect( 'func_1' )
	->once()
	->with(
		[
			'arg1' => Mockery::type( 'string' ),
		]
	)
	->andReturn( true );

$this->assertTrue( func_1( [ 'arg1' => 'krya' ] ) );
```

`Mockery::type( ... )` works only for first level of arguments.

**Comment by gmazzap** [comment]
Hi @wppunk 

This is handled by Mockery, are you sure that is valid Mockery syntax?

**Comment by wppunk** [comment]
@gmazzap Unfortunately, but it doesn't work in the Mockery

**Comment by gmazzap** [comment]
Sorry, you mean is not supported by [Mockery](https://github.com/mockery/mockery)?

In that case you should open a ticket for them. Or use validation via closure: http://docs.mockery.io/en/latest/reference/argument_validation.html#complex-argument-validation

**Comment by wppunk** [comment]
@gmazzap Yep, I've created the [issue](https://github.com/mockery/mockery/issues/1098)

**Comment by gmazzap** [comment]
Thanks. So I'm closing this. In case they introduce that funcitonality, it will land on Brain Monkey automatically, since this just wrap that.
