### ISSUE TITLE
Docs site not up-to-date

### ISSUE THREAD

**Issue by andronocean** [Brain-WP/BrainMonkey#98]
It looks like the docs site https://brain-wp.github.io/BrainMonkey/ hasn't been updated with the latest info — for example, the changes made in #79. I was reading it today, and noticed it still offered the `self::assertTrue( has_filter(...))` syntax. The newest versions within the repo itself are different.

Thank you very much for this awesome tool :)

**Comment by gmazzap** [comment]
Hi @andronocean the updated docs are here https://giuseppe-mazzapica.gitbook.io/brain-monkey/ they are linked in the repo's "About" section.

I'll probably need to setup a redirect from old docs...

**Comment by andronocean** [comment]
Oooh, nice! I'd bookmarked the old ones when I first discovered BrainMonkey, just kept going back there. Redirect would be great, since there's a number of links across the web pointing there.

**Comment by henryobiaraije** [comment]
It looks like the redirect has not been set yet and as a result, it takes time for beginners to figure this out because the doc is different from how the library works.

**Comment by gmazzap** [comment]
Thanks for the reminder, redirect is now setup
